# Generated by Django 5.0.6 on 2024-05-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg_analysis', '0002_alter_diagnosis_ecg_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecgdata',
            old_name='ecg_file',
            new_name='ecg_file1',
        ),
        migrations.AddField(
            model_name='ecgdata',
            name='ecg_file2',
            field=models.FileField(blank=True, null=True, upload_to='ecg_files/'),
        ),
    ]
